version: '3.7'

services:

  hello-world:
    container_name: hello-world
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true  
    stdin_open: true   